# Generated by Django 5.1.2 on 2024-11-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_default_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationschedule',
            name='updated_at',
        ),
    ]
