name: Django CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configuração do Docker e Docker Compose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "docker-compose.yml"

      # Rodar os testes
      - name: Run tests
        run: |
          docker exec django_api_mensageria test tests